name: BuildAgentImage

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: []

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: https://raw.githubusercontent.com/actions/runner-images/main/images/linux/ubuntu2204.pkr.hcl

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: https://raw.githubusercontent.com/actions/runner-images/main/images/linux/ubuntu2204.pkr.hcl
          working_directory: infrastructure/packer
        env:
          PACKER_LOG: 1
          HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
          HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
