name: BuildAgentImage

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: []

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - run: git clone https://github.com/actions/runner-images.git
        
      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: ubuntu2204.pkr.hcl
          working_directory: runner-images/images/linux/

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: ubuntu2204.pkr.hcl
          working_directory: runner-images/images/linux/
        env:
          PACKER_LOG: 1
          ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          PKR_VAR_client_secret: ${{ secrets.CLIENT_SECRET }}
          ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          ARM_RESOURCE_GROUP: ${{ secrets.MANAGED_IMAGE_RESOURCE_GROUP_NAME }}
          ARM_STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          # new RG
          #TEMP_RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
          #ARM_RESOURCE_LOCATION: West Europe
          # existing RG
          PKR_VAR_build_resource_group_name: ${{ secrets.RESOURCE_GROUP_NAME }}
